crnk:
  resourcePackage: com.codenotfound.crnk.domain
  domainName: http://localhost:9090/springboot
  pathPrefix: /api

server:
  context-path: /springboot
  port: 9090

properties:
  countryMap:
    SG: Singapore
    HK: HongKong